### ISSUE TITLE
Build (error)

### ISSUE THREAD

**Issue by einlichtvogel** [alexthemaster/action-build-typescript#9]
Hey, I just installed the Action and wrote an script for it: https://just-paste.it/Ph0as44dv3, with the output: https://just-paste.it/WbrwVqa291 .

You can see that the output says that nothin has been committed, is this my fault, or your's

**Comment by alexthemaster** [comment]
Hey! As the logs say, a new commit wasn't made because the files in the branch up to date. 
From what I can see in your repo, tsc is compiling the TS files into a ["dist" folder](https://github.com/iqstreamlightsync/dsbmobile.js/blob/master/tsconfig.json#L9), but your .gitignore is set to [ignore](https://github.com/iqstreamlightsync/dsbmobile.js/blob/master/.gitignore#L2) any `dist` folders.

**Comment by einlichtvogel** [comment]
oh I totally forgot that, thanks a lot @alexthemaster!
